FROM quay.io/modh/odh-generic-data-science-notebook@sha256:e2cab24ebe935d87f7596418772f5a97ce6a2e747ba0c1fd4cec08a728e99403

COPY requirements.txt ./

RUN echo "Installing softwares and packages" && \
rm -f ./requirements.txt
