FROM quay.io/modh/odh-generic-data-science-notebook

COPY requirements.txt ./

RUN echo "Installing softwares and packages" && \
pip install micropipenv && \
micropipenv install && \
rm -f ./requirements.txt
